### ISSUE TITLE
add more colors

### ISSUE THREAD

**Issue by 2Oozbeh** [bderrly/braincurses#1]
Hi
I really love this game. It's #1 in all the mastermind games. 
Can you add an option that player will be able to play game with 5 colors (5 places for guess) instead of 4 colors ?
Thank you.

**Comment by bderrly** [comment]
Yeah, that is something I can work on. I have been thinking about updating the look a bit. I intentionally made the board fit in an 80x24 screen size, but I may give that up and make it size dynamically based on the size of the terminal.

**Comment by bderrly** [comment]
I pushed some changes today that add command-line flags to alter the length of the secret code. You can pass -c with an integer between 4 and 6 inclusive. Let me know how it works for you.

**Comment by 2Oozbeh** [comment]
I try, it work pefectly. Oh my god! 6 places!!! very hard maybe the rows should be more than 10 in 6 colors mode . Ha Ha I love it :+1:
I think it's good if the player will be able to save current position and play it later. 
Thank you very much.

**Comment by bderrly** [comment]
There is also a -g (guesses) flag that allows you to go up to 15 guesses.
